name: mealplanner

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    networks:
      - mealplanner
    environment:
      - TSX_WATCH=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=500

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - mealplanner
    ports:
      - '3000:3000'
    depends_on:
      - server

networks:
  mealplanner:
    driver: bridge
